export const pieTokens = {
  color: {
    bgPrimary: "var(--pie-bg-primary)",
    bgSecondary: "var(--pie-bg-secondary)",
    bgTertiary: "var(--pie-bg-tertiary)",
    textPrimary: "var(--pie-text-primary)",
    textSecondary: "var(--pie-text-secondary)",
    textTertiary: "var(--pie-text-tertiary)",
    textOnAccent: "var(--pie-text-on-accent)",
    line: "var(--pie-line)",
    lineStrong: "var(--pie-line-strong)",
    borderSecondary: "var(--pie-border-secondary)",
    accent: "var(--pie-accent)",
    accentHover: "var(--pie-accent-hover)",
    accentPressed: "var(--pie-accent-pressed)",
    accentWeak: "var(--pie-accent-weak)",
    success: "var(--pie-success)",
    warning: "var(--pie-warning)",
    danger: "var(--pie-danger)",
    dangerWeak: "var(--pie-danger-weak)",
    focus: "var(--pie-focus)",
  },
  font: {
    sans: "var(--pie-font-sans)",
    heading: "var(--pie-font-heading)",
    mono: "var(--pie-font-mono)",
  },
  textSize: {
    xs: "var(--pie-text-xs)",
    sm: "var(--pie-text-sm)",
    base: "var(--pie-text-base)",
    lg: "var(--pie-text-lg)",
    xl: "var(--pie-text-xl)",
  },
  radius: {
    sm: "var(--pie-radius-sm)",
    md: "var(--pie-radius-md)",
    smooth: "var(--pie-radius-smooth)",
    lg: "var(--pie-radius-lg)",
    xl: "var(--pie-radius-xl)",
    full: "var(--pie-radius-full)",
  },
  space: {
    1: "var(--pie-space-1)",
    2: "var(--pie-space-2)",
    3: "var(--pie-space-3)",
    4: "var(--pie-space-4)",
    5: "var(--pie-space-5)",
    6: "var(--pie-space-6)",
    8: "var(--pie-space-8)",
    10: "var(--pie-space-10)",
    12: "var(--pie-space-12)",
  },
  shadow: {
    min: "var(--pie-shadow-min)",
    sm: "var(--pie-shadow-sm)",
    md: "var(--pie-shadow-md)",
    lg: "var(--pie-shadow-lg)",
  },
  motion: {
    fast: "var(--pie-motion-fast)",
    medium: "var(--pie-motion-medium)",
    slow: "var(--pie-motion-slow)",
    easeDefault: "var(--pie-ease-default)",
    easeEmphasized: "var(--pie-ease-emphasized)",
  },
} as const;

export type PieTokens = typeof pieTokens;
